declare module 'html2pdf.js'
declare module 'react-beautiful-dnd'
declare module 'react-chartjs-2'
declare module '@radix-ui/react-icons'
declare module 'jspdf'
declare module 'prismjs'
declare module 'papaparse'